import type { ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';

import '@/styles/global.scss';
import '@/styles/reset.scss';

const PPMachina = localFont({
	src: [
		{
			path: './_fonts/PPNeueMachina-InktrapRegular.otf',
			weight: '400',
			style: 'normal',
		},
		{
			path: './_fonts/PPNeueMachina-InktrapUltrabold.otf',
			weight: '800',
			style: 'normal',
		},
	],
	variable: '--font-ppmachina',
	display: 'swap',
	fallback: ['sans-serif'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	viewportFit: 'cover',
	userScalable: false,
};

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
	return (
		<html className={PPMachina.variable} lang="en">
			<body>
				<div id={'app-root'}>
					{/*<Header />*/}
					<main className={'main'}>{children}</main>
					{/*<Footer />*/}
				</div>
				{/*<AppLoader />*/}
			</body>
		</html>
	);
};

RootLayout.displayName = 'RootLayout';

export default RootLayout;
