import type { ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';
import localFont from 'next/font/local';

import { MocksProvider } from '@/components/utils';
import { Footer, Header } from '@/components/widgets';
import config from '@/constants/config';

import { AppLoader } from './_app-loader';

import '@/styles/global.scss';
import '@/styles/reset.scss';

const Inter = localFont({
  src: './_fonts/InterVariable.woff2',
  weight: '100 900',
  variable: '--font-inter',
  fallback: ['sans-serif'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  viewportFit: 'cover',
  userScalable: false,
};

if (config.api.mocks && process.env.NEXT_RUNTIME === 'nodejs') {
  const { server } = await import('@/mocks/node');
  server.listen();
}

const RootLayout = ({ children }: Readonly<{ children: ReactNode }>) => {
  return (
    <html className={`${Inter.variable}`} lang="en">
      <body>
        <MocksProvider>
          <div id={'app-root'}>
            <Header />
            <main className={'main'}>{children}</main>
            <Footer />
          </div>
          <AppLoader />
        </MocksProvider>
      </body>
    </html>
  );
};

RootLayout.displayName = 'RootLayout';

export default RootLayout;
